# Generated by Django 4.1.7 on 2023-04-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0005_alter_delivery_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='user',
        ),
    ]
