# Generated by Django 4.1.7 on 2023-06-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0006_remove_delivery_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
        migrations.AlterModelTable(
            name='delivery',
            table='delivery',
        ),
        migrations.AlterModelTable(
            name='item',
            table='item',
        ),
    ]
