# Generated by Django 4.1.7 on 2023-04-12 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=300)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('is_vegeterian', models.BooleanField(default=False)),
                ('Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.category')),
            ],
        ),
    ]
