# Generated by Django 4.1.7 on 2023-04-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='Category_id',
            new_name='category',
        ),
    ]
