# Generated by Django 4.1.7 on 2023-06-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_alter_dish_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='dish',
            table='dish',
        ),
    ]
